"""The shell script template used by the `dts_test` rule.

Kept as a `.bzl` string constant (rather than a data file target) so that
consumers of `dts_test` never have to load the `//internal` BUILD package and
its documentation-only (`stardoc`) dependencies.
"""

DTS_TEST_TEMPLATE = """#!/usr/bin/env bash
# Generated by the dts_test rule. Do not edit.
set -uo pipefail

# --- begin runfiles.bash initialization v3 ---
# Copy-pasted from the Bazel Bash runfiles library v3.
set +e
f=bazel_tools/tools/bash/runfiles/runfiles.bash
# shellcheck disable=SC1090
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \\
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \\
  source "$0.runfiles/$f" 2>/dev/null || \\
  source "$(grep -sm1 "^$f " "$0.runfiles/MANIFEST" | cut -f2- -d' ')" 2>/dev/null || \\
  source "$(grep -sm1 "^$f " "$0.exe.runfiles/MANIFEST" | cut -f2- -d' ')" 2>/dev/null || \\
  { echo >&2 "ERROR: cannot find $f"; exit 1; }
set -e
# --- end runfiles.bash initialization v3 ---

FDTGET="$(rlocation "%FDTGET%")"
FDTDUMP="$(rlocation "%FDTDUMP%")"
DTB="$(rlocation "%DTB%")"

status=0

check() {
  local node="$1" prop="$2" want="$3" got
  got="$("${FDTGET}" "${DTB}" "${node}" "${prop}" 2>/dev/null || true)"
  if [[ "${got}" != "${want}" ]]; then
    echo "FAIL: ${node} ${prop}: want [${want}] got [${got}]" >&2
    status=1
  else
    echo "OK:   ${node} ${prop} = ${got}"
  fi
}

dump() {
  echo "fdtdump ${DTB}:"
  "${FDTDUMP}" "${DTB}"
}

%ASSERTIONS%
%DUMP%

if [[ "${status}" -ne 0 ]]; then
  echo "device tree assertions FAILED" >&2
else
  echo "device tree assertions PASSED"
fi
exit "${status}"
"""
